### ISSUE TITLE
Missing function: logits_to_idxs

### ISSUE THREAD

**Issue by Zehui127** [Genentech/regLM#1]
Dear Team,

Merry Christmas, I have been trying to run the training script but encounter errors when running the model.generate function. I narrowed it down and find that there is an undefined function ```logits_to_idxs``` got used in the generate function of torch.lightning module. Could you please provide the definition of this function?

Best,
Zehui Li

**Comment by avantikalal** [comment]
Resolved with the latest commit. Please update the code and you should be able to follow the tutorial.
