### ISSUE TITLE
404 when trying to download JASPAR PPMs

### ISSUE THREAD

**Issue by yangzhao1230** [Genentech/regLM#2]
![image](https://github.com/user-attachments/assets/7f914618-418b-4d73-97d7-4ba1873a4f7a)

**Comment by avantikalal** [comment]
Hi @yangzhao1230 , unfortunately that file does not exist any longer. You can recreate it by clicking on the "download" link here: https://jaspar.elixir.no/search?q=&collection=CORE&tax_group=fungi&tax_id=4932&type=all&class=all&family=all&version=latest

**Comment by ashok-arora** [comment]
@avantikalal Could you please mention which profiles to download? Also, it only has `*_meme.txt` file, is there someplace else for downloading `selected_ppms.csv`?

**Comment by avantikalal** [comment]
Hi @ashok-arora, if you want to recreate the file `selected_ppms.csv` containing selected yeast motifs, you should download all 170 motifs selected in https://jaspar.elixir.no/search?q=&collection=CORE&tax_group=fungi&tax_id=4932&type=all&class=all&family=all&version=latest in a combined *_meme.txt file. To create the`selected_ppms.csv` file, follow the notebook `human_enhancers/01_data_processing/02_get_jaspar_ppms.ipynb` from Zenodo: https://zenodo.org/records/12668907

**Comment by ashok-arora** [comment]
Oh nice, thank you @avantikalal.

**Comment by ashok-arora** [comment]
@avantikalal and which link to follow for `human_enhancer` motifs, would the same ones work or would I need seperate? also, is `*_tfbs_freq_all.csv` available in zenodo too?

**Comment by avantikalal** [comment]
Sorry for the confusion.

For yeast motifs:
Download .meme.txt file: https://jaspar.elixir.no/search?q=&collection=CORE&tax_group=fungi&tax_id=4932&type=all&class=all&family=all&version=latest
Process it: yeast_promoters/01_data_processing/03_get_jaspar_ppms.ipynb

For human motifs:

Download .meme.txt file: https://jaspar.elixir.no/search?q=&collection=CORE&tax_group=vertebrates&tax_id=9606&type=all&class=all&family=all&version=latest
Process it: human enhancers/01_data_processing/02_get_jaspar_ppms.ipynb
